In [1]:
import pandas as pd

df = pd.read_csv('./clean/melted_estat_hlth_cd_aro_ISO2.csv')
df.head()

  ISO2  country     cause    age      sex  year  deaths  percentage
0   AT  Austria  COVID-19     65  Females  2016     0.0         0.0
1   AT  Austria  COVID-19     65    Males  2016     0.0         0.0
2   AT  Austria  COVID-19     65    Total  2016     0.0         0.0
3   AT  Austria  COVID-19  15-29  Females  2016     0.0         0.0
4   AT  Austria  COVID-19  15-29    Males  2016     0.0         0.0

In [2]:
df['age'] = df['age'].replace({'15': '15-64', '15-29': '15-64', '30-44': '15-64', '45-64': '15-64'})
df_grouped = df.groupby(['ISO2', 'country', 'cause', 'age', 'sex', 'year']).sum().reset_index()
df_grouped.head()

  ISO2  country     cause    age      sex  year  deaths  percentage
0   AT  Austria  COVID-19  15-64  Females  2016     0.0    0.000000
1   AT  Austria  COVID-19  15-64  Females  2017     0.0    0.000000
2   AT  Austria  COVID-19  15-64  Females  2018     0.0    0.000000
3   AT  Austria  COVID-19  15-64  Females  2019     0.0    0.000000
4   AT  Austria  COVID-19  15-64  Females  2020   127.0    0.139617

In [3]:
# df_grouped.to_csv('./clean/melted_estat_hlth_cd_aro_ISO2_NEW.csv', index=False)

In [6]:
swe = df[df.country == 'Sweden']
swe

      ISO2 country           cause    age      sex  year  deaths  percentage
25056   SE  Sweden        COVID-19     65  Females  2016     0.0         0.0
25057   SE  Sweden        COVID-19     65    Males  2016     0.0         0.0
25058   SE  Sweden        COVID-19     65    Total  2016     0.0         0.0
25059   SE  Sweden        COVID-19  15-64  Females  2016     0.0         0.0
25060   SE  Sweden        COVID-19  15-64    Males  2016     0.0         0.0
...    ...     ...             ...    ...      ...   ...     ...         ...
25915   SE  Sweden  Use of alcohol  15-64    Males  2023     NaN         NaN
25916   SE  Sweden  Use of alcohol  15-64    Total  2023     NaN         NaN
25917   SE  Sweden  Use of alcohol  Total  Females  2023     NaN         NaN
25918   SE  Sweden  Use of alcohol  Total    Males  2023     NaN         NaN
25919   SE  Sweden  Use of alcohol  Total    Total  2023     NaN         NaN

[864 rows x 8 columns]

In [11]:
swe[(swe.year < 2020) & ((swe.cause == "Mental and behavioural disorders") | (swe.cause == "Intentional self-harm ")) & (swe.age=="15-64")]

,ISO2,country,cause,age,sex,year,deaths,percentage
25113,SE,Sweden,Mental and behavioural disorders,15-64,Females,2016,4.0,0.004415
25114,SE,Sweden,Mental and behavioural disorders,15-64,Males,2016,2.0,0.002207
25115,SE,Sweden,Mental and behavioural disorders,15-64,Total,2016,6.0,0.006622
25116,SE,Sweden,Mental and behavioural disorders,15-64,Females,2016,0.0,0.000000
25117,SE,Sweden,Mental and behavioural disorders,15-64,Males,2016,0.0,0.000000
25118,SE,Sweden,Mental and behavioural disorders,15-64,Total,2016,0.0,0.000000
25119,SE,Sweden,Mental and behavioural disorders,15-64,Females,2016,0.0,0.000000
25120,SE,Sweden,Mental and behavioural disorders,15-64,Males,2016,0.0,0.000000
25121,SE,Sweden,Mental and behavioural disorders,15-64,Total,2016,0.0,0.000000
25122,SE,Sweden,Mental and behavioural disorders,15-64,Females,2016,0.0,0.000000
25123,SE,Sweden,Mental and behavioural disorders,15-64,Males,2016,2.0,0.002207
25124,SE,Sweden,Mental and behavioural disorders,15-64,Total,2016,2.0,0.002207
25221,SE,Sweden,Mental and behavioural disorders,15-64,Females,2017,4.0,0.004365
25222,SE,Sweden,Mental and behavioural disorders,15-64,Males,2017,2.0,0.002183
25223,SE,Sweden,Mental and behavioural disorders,15-64,Total,2017,6.0,0.006548
25224,SE,Sweden,Mental and behavioural disorders,15-64,Females,2017,0.0,0.000000
25225,SE,Sweden,Mental and behavioural disorders,15-64,Males,2017,0.0,0.000000
25226,SE,Sweden,Mental and behavioural disorders,15-64,Total,2017,0.0,0.000000
25227,SE,Sweden,Mental and behavioural disorders,15-64,Females,2017,0.0,0.000000
25228,SE,Sweden,Mental and behavioural disorders,15-64,Males,2017,0.0,0.000000
25229,SE,Sweden,Mental and behavioural disorders,15-64,Total,2017,0.0,0.000000
25230,SE,Sweden,Mental and behavioural disorders,15-64,Females,2017,0.0,0.000000
25231,SE,Sweden,Mental and behavioural disorders,15-64,Males,2017,0.0,0.000000
25232,SE,Sweden,Mental and behavioural disorders,15-64,Total,2017,0.0,0.000000
25329,SE,Sweden,Mental and behavioural disorders,15-64,Females,2018,3.0,0.003269
25330,SE,Sweden,Mental and behavioural disorders,15-64,Males,2018,3.0,0.003269
25331,SE,Sweden,Mental and behavioural disorders,15-64,Total,2018,6.0,0.006538
25332,SE,Sweden,Mental and behavioural disorders,15-64,Females,2018,0.0,0.000000
25333,SE,Sweden,Mental and behavioural disorders,15-64,Males,2018,0.0,0.000000
25334,SE,Sweden,Mental and behavioural disorders,15-64,Total,2018,0.0,0.000000
25335,SE,Sweden,Mental and behavioural disorders,15-64,Females,2018,0.0,0.000000
25336,SE,Sweden,Mental and behavioural disorders,15-64,Males,2018,0.0,0.000000
25337,SE,Sweden,Mental and behavioural disorders,15-64,Total,2018,0.0,0.000000
25338,SE,Sweden,Mental and behavioural disorders,15-64,Females,2018,4.0,0.004359
25339,SE,Sweden,Mental and behavioural disorders,15-64,Males,2018,2.0,0.002179
25340,SE,Sweden,Mental and behavioural disorders,15-64,Total,2018,6.0,0.006538
25437,SE,Sweden,Mental and behavioural disorders,15-64,Females,2019,5.0,0.005659
25438,SE,Sweden,Mental and behavioural disorders,15-64,Males,2019,2.0,0.002264
25439,SE,Sweden,Mental and behavioural disorders,15-64,Total,2019,7.0,0.007923
25440,SE,Sweden,Mental and behavioural disorders,15-64,Females,2019,0.0,0.000000
25441,SE,Sweden,Mental and behavioural disorders,15-64,Males,2019,0.0,0.000000
25442,SE,Sweden,Mental and behavioural disorders,15-64,Total,2019,0.0,0.000000
25443,SE,Sweden,Mental and behavioural disorders,15-64,Females,2019,0.0,0.000000
25444,SE,Sweden,Mental and behavioural disorders,15-64,Males,2019,0.0,0.000000
25445,SE,Sweden,Mental and behavioural disorders,15-64,Total,2019,0.0,0.000000
25446,SE,Sweden,Mental and behavioural disorders,15-64,Females,2019,2.0,0.002264
25447,SE,Sweden,Mental and behavioural disorders,15-64,Males,2019,0.0,0.000000
25448,SE,Sweden,Mental and behavioural disorders,15-64,Total,2019,2.0,0.002264

In [21]:
pol = df_grouped[df_grouped.country=="Germany"]
pol = pol[(pol.cause == "Mental and behavioural disorders") | (pol.cause == "Intentional self-harm ")]
pol

,ISO2,country,cause,age,sex,year,deaths,percentage
2808,DE,Germany,Mental and behavioural disorders,15-64,Females,2016,50.0,0.005473
2809,DE,Germany,Mental and behavioural disorders,15-64,Females,2017,48.0,0.005135
2810,DE,Germany,Mental and behavioural disorders,15-64,Females,2018,54.0,0.005639
2811,DE,Germany,Mental and behavioural disorders,15-64,Females,2019,52.0,0.005518
2812,DE,Germany,Mental and behavioural disorders,15-64,Females,2020,1353.0,0.136942
...,...,...,...,...,...,...,...,...
2875,DE,Germany,Mental and behavioural disorders,Total,Total,2019,60016.0,6.369036
2876,DE,Germany,Mental and behavioural disorders,Total,Total,2020,62325.0,6.308147
2877,DE,Germany,Mental and behavioural disorders,Total,Total,2021,62994.0,6.139491
2878,DE,Germany,Mental and behavioural disorders,Total,Total,2022,72243.0,6.754940
2879,DE,Germany,Mental and behavioural disorders,Total,Total,2023,0.0,0.000000